# Generated by Django 4.1.5 on 2023-01-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
            ],
        ),
    ]
