# Generated by Django 4.1.5 on 2023-01-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
